---
- hosts: all
  tasks:
  - name: Install httpd Package
    yum: name=mysql state=latest
  - name: Start and Enable mysql service
    service: name=mysql state=restarted enabled=yes

  become: yes
 
  vars_files:
 
    - vars/main.yml
 
  roles:
 
    - { role: geerlingguy.mysql }
